//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPOINTMENT
    {
        public APPOINTMENT()
        {
            this.BOOKS = new HashSet<BOOK>();
        }
    
        public string APPOIN_STATE { get; set; }
        public string APPOIN_START_DATE { get; set; }
        public decimal APPOIN_MAX_PATIENTS { get; set; }
        public string APPOIN_END_DATE { get; set; }
        public decimal DOC_ID { get; set; }
        public decimal CLNC_ID { get; set; }
        public decimal APPOIN_ID { get; set; }
    
        public virtual DOCTOR DOCTOR { get; set; }
        public virtual CLINIC CLINIC { get; set; }
        public virtual ICollection<BOOK> BOOKS { get; set; }
    }
}
