//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class AREA
    {
        public AREA()
        {
            this.PATIENTs = new HashSet<PATIENT>();
            this.CLINICs = new HashSet<CLINIC>();
        }
    
        public decimal AREA_ID { get; set; }
        public string AREA_NAME { get; set; }
    
        public virtual ICollection<PATIENT> PATIENTs { get; set; }
        public virtual ICollection<CLINIC> CLINICs { get; set; }
    }
}
