//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK
    {
        public string BOOK_STATE { get; set; }
        public decimal PATIENT_ID { get; set; }
        public string APPOIN_START_DATE { get; set; }
        public decimal DOC_ID { get; set; }
        public decimal CLNC_ID { get; set; }
        public string APPOIN_END_DATE { get; set; }
        public Nullable<decimal> TYPE_ID { get; set; }
    
        public virtual APPOINTMENT APPOINTMENT { get; set; }
        public virtual BOOK_TYPE BOOK_TYPE { get; set; }
        public virtual PATIENT PATIENT { get; set; }
    }
}
