//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK_TYPE
    {
        public BOOK_TYPE()
        {
            this.BOOKS = new HashSet<BOOK>();
        }
    
        public string TYPE_NAME { get; set; }
        public decimal TYPE_ID { get; set; }
    
        public virtual ICollection<BOOK> BOOKS { get; set; }
    }
}
