//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLINIC
    {
        public CLINIC()
        {
            this.ADMINs = new HashSet<ADMIN>();
            this.CLINICREVIEWs = new HashSet<CLINICREVIEW>();
            this.CLNCTELS = new HashSet<CLNCTEL>();
            this.APPOINTMENTs = new HashSet<APPOINTMENT>();
        }
    
        public decimal CLNC_ID { get; set; }
        public string CLNC_NAME { get; set; }
        public string CLNC_ADDRESS { get; set; }
        public string CLNC_EMAIL { get; set; }
        public decimal AREA_ID { get; set; }
    
        public virtual ICollection<ADMIN> ADMINs { get; set; }
        public virtual AREA AREA { get; set; }
        public virtual ICollection<CLINICREVIEW> CLINICREVIEWs { get; set; }
        public virtual ICollection<CLNCTEL> CLNCTELS { get; set; }
        public virtual ICollection<APPOINTMENT> APPOINTMENTs { get; set; }
    }
}
