//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTOR
    {
        public DOCTOR()
        {
            this.DOCTELS = new HashSet<DOCTEL>();
            this.DOCTORREVIEWs = new HashSet<DOCTORREVIEW>();
            this.APPOINTMENTs = new HashSet<APPOINTMENT>();
        }
    
        public string DOC_GENDER { get; set; }
        public string DOC_EMAIL { get; set; }
        public string DOC_ADDRESS { get; set; }
        public string DOC_NAME { get; set; }
        public decimal DOC_ID { get; set; }
        public string DOC_STATE { get; set; }
        public decimal SPEC_ID { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual ICollection<DOCTEL> DOCTELS { get; set; }
        public virtual SPECIALTY SPECIALTY { get; set; }
        public virtual ICollection<DOCTORREVIEW> DOCTORREVIEWs { get; set; }
        public virtual ICollection<APPOINTMENT> APPOINTMENTs { get; set; }
    }
}
