//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATIENT
    {
        public PATIENT()
        {
            this.CLINICREVIEWs = new HashSet<CLINICREVIEW>();
            this.DOCTORREVIEWs = new HashSet<DOCTORREVIEW>();
            this.BOOKS = new HashSet<BOOK>();
        }
    
        public decimal PATIENT_ID { get; set; }
        public string PATIENT_EMAIL { get; set; }
        public string PATIENT_NAME { get; set; }
        public string PATIENT_TEL { get; set; }
        public string PATIENT_ADDRESS { get; set; }
        public decimal AREA_ID { get; set; }
        public string PATIENT_PASSWORD { get; set; }
    
        public virtual AREA AREA { get; set; }
        public virtual ICollection<CLINICREVIEW> CLINICREVIEWs { get; set; }
        public virtual ICollection<DOCTORREVIEW> DOCTORREVIEWs { get; set; }
        public virtual ICollection<BOOK> BOOKS { get; set; }
    }
}
