//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADMIN> ADMINs { get; set; }
        public DbSet<AREA> AREAs { get; set; }
        public DbSet<CLINIC> CLINICs { get; set; }
        public DbSet<CLINICREVIEW> CLINICREVIEWs { get; set; }
        public DbSet<CLNCTEL> CLNCTELS { get; set; }
        public DbSet<DOCTEL> DOCTELS { get; set; }
        public DbSet<DOCTORREVIEW> DOCTORREVIEWs { get; set; }
        public DbSet<PATIENT> PATIENTs { get; set; }
        public DbSet<SPECIALTY> SPECIALTies { get; set; }
        public DbSet<DOCTOR> DOCTORs { get; set; }
        public DbSet<BOOK_TYPE> BOOK_TYPE { get; set; }
        public DbSet<APPOINTMENT> APPOINTMENTs { get; set; }
        public DbSet<BOOK> BOOKS { get; set; }
    
        public virtual int GET_AREA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_AREA");
        }
    }
}
